server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: test
    group:
      test: test,oauth,mail
      develop: develop,oauth,mail,devdb
      production: production,oauth,mail,proddb