server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: test
    group:
      test: oauth
      develop: oauth,devdb
      production: oauth,proddb

#spring:
# config:
#  activate:
#   on-profile: test

---
spring:
  config:
    activate:
      on-profile: test
  sql:
    init:
      schema-locations: classpath:db/sql/schema-h2.sql
      data-locations: classpath:db/sql/data-h2.sql
      mode: always
  thymeleaf:
    cache: 'false'
  freemarker:
    cache: 'false'
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: 'true'
  h2:
    console:
      enabled: 'true'
  devtools:
    livereload:
      enabled: 'true'
  messages:
    basename: messages,errors
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG

---
spring:
  config:
    activate:
      on-profile: develop
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: 'false'
  freemarker:
    cache: 'false'
  devtools:
    livereload:
      enabled: 'true'
  messages:
    basename: messages,errors
---
spring:
  config:
    activate:
      on-profile: production
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: 'false'
  freemarker:
    cache: 'false'
  devtools:
    livereload:
      enabled: 'true'
  messages:
    basename: messages,errors